// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d9f759f4-7dc3-412d-a3fe-f8aa1e9425ca",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_s0tRtqBNS",
    "aws_user_pools_web_client_id": "3b8ar6tvr9l75hat4a0a0lbi57"
};


export default awsmobile;
