// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-2",
  "aws_cognito_identity_pool_id": "us-east-2:72f40bc0-8bce-44da-9107-09958dae9ee4",
  "aws_cognito_region": "us-east-2",
  "aws_user_pools_id": "us-east-2_TzdEIsi8d",
  "aws_user_pools_web_client_id": "3l1mn6mq9ccglp6n9n13n9bn5k"
};


export default awsmobile;